import { defineStore } from 'pinia'

export const externalLinks = {
  substack: 'https://agileperiodization.substack.com/',
  skool: 'https://www.skool.com/agileperiodization',
  payhip: 'https://payhip.com/mjovanovic',
  amazon: 'https://amzn.to/4bQPUeM',
  complementary: 'https://complementarytraining.com/',
  linkedin: 'https://www.linkedin.com/in/mladenjovanovic/',
  instagram: 'https://www.instagram.com/physical_prep/',
  github: 'https://github.com/mladenjovanovic',
}

export const useContentStore = defineStore('content', {
  state: () => ({
    posts: [
      {
        id: 'p1',
        title: 'Planning with intent, adjusting without panic',
        dek: 'On the difference between a plan and the act of planning — and why the latter is what keeps coaches honest when the week starts breaking apart.',
        category: 'Essay',
        readTime: '12 min',
        date: 'Apr 28, 2026',
        seed: 1,
        variant: 'feature',
        href: externalLinks.substack,
      },
      {
        id: 'p2',
        title: 'Why most periodization models fail in the real world',
        dek: 'A field-tested look at where textbook templates collapse on contact with athletes, calendars, and weather.',
        category: 'Essay',
        readTime: '9 min',
        date: 'Apr 11, 2026',
        seed: 2,
        variant: 'standard',
        href: externalLinks.substack,
      },
      {
        id: 'p3',
        title: 'Monitoring what matters',
        dek: 'A practical framework for choosing the few signals you can actually act on.',
        category: 'Tools',
        readTime: '14 min',
        date: 'Mar 24, 2026',
        seed: 3,
        variant: 'standard',
        href: externalLinks.substack,
      },
      {
        id: 'p4',
        title: 'Reading athletes: a field guide',
        dek: 'What to look for before you ever open the spreadsheet.',
        category: 'Field Notes',
        readTime: '7 min',
        date: 'Mar 09, 2026',
        seed: 4,
        variant: 'standard',
        href: externalLinks.substack,
      },
      {
        id: 'p5',
        title: 'Decision-making when the data is noisy',
        dek: 'Heuristics, priors, and the cost of false certainty.',
        category: 'Essay',
        readTime: '11 min',
        date: 'Feb 22, 2026',
        seed: 5,
        variant: 'standard',
        href: externalLinks.substack,
      },
      {
        id: 'p6',
        title: 'Skill acquisition for strength coaches',
        category: 'Field Notes',
        readTime: '6 min',
        date: 'Feb 03, 2026',
        seed: 6,
        variant: 'text',
        href: externalLinks.substack,
      },
      {
        id: 'p7',
        title: 'The architecture of adaptation',
        category: 'Essay',
        readTime: '10 min',
        date: 'Jan 18, 2026',
        seed: 7,
        variant: 'text',
        href: externalLinks.substack,
      },
    ],

    products: [
      {
        id: 's1',
        type: 'Course',
        category: 'courses',
        title: 'Agile Periodization — Foundations',
        blurb: 'A six-module video course on the operating framework behind real-world periodization.',
        price: '€249',
        seed: 11,
        href: externalLinks.payhip,
      },
      {
        id: 's2',
        type: 'Course',
        category: 'courses',
        title: 'Planning the Block, Not the Year',
        blurb: 'Short-cycle structure, adjustment heuristics, and decision logs.',
        price: '€149',
        seed: 12,
        href: externalLinks.payhip,
      },
      {
        id: 's3',
        type: 'Book',
        category: 'books',
        title: 'Strength Training Manual',
        blurb: 'The two-volume reference on programming logic, set-and-rep schemes, and progression.',
        price: '€59',
        seed: 13,
        href: externalLinks.amazon,
      },
      {
        id: 's4',
        type: 'Book',
        category: 'books',
        title: 'Bayesian Inference for Coaches',
        blurb: 'A coach-friendly introduction to thinking in probabilities.',
        price: '€34',
        seed: 14,
        href: externalLinks.amazon,
      },
      {
        id: 's5',
        type: 'Template',
        category: 'tools',
        title: 'Microcycle Planner',
        blurb: 'A working spreadsheet for laying out a week with intent, then adjusting it on Wednesday.',
        price: '€29',
        seed: 15,
        href: externalLinks.payhip,
      },
      {
        id: 's6',
        type: 'Template',
        category: 'tools',
        title: 'Athlete Monitoring Log',
        blurb: 'Wellness, load, readiness, and free-text notes in one practical sheet.',
        price: '€19',
        seed: 16,
        href: externalLinks.payhip,
      },
      {
        id: 's7',
        type: 'App',
        category: 'tools',
        title: 'AthletePulse',
        blurb: 'A lightweight tracking tool for daily readiness and weekly trends.',
        price: '€9 / mo',
        seed: 17,
        href: externalLinks.payhip,
      },
      {
        id: 's8',
        type: 'App',
        category: 'tools',
        title: 'LoadGraph',
        blurb: 'Plot acute and chronic load with a couple of clicks — built for terminal coaches.',
        price: '€12 / mo',
        seed: 18,
        href: externalLinks.payhip,
      },
      {
        id: 's9',
        type: 'Bundle',
        category: 'products',
        title: 'The Practitioner Bundle',
        blurb: 'Foundations course, both planner templates, and a year of AthletePulse.',
        price: '€349',
        seed: 19,
        href: externalLinks.payhip,
      },
      {
        id: 's10',
        type: 'Bundle',
        category: 'products',
        title: 'The Library Bundle',
        blurb: 'Every book and every essay collection — a single archive download.',
        price: '€129',
        seed: 20,
        href: externalLinks.payhip,
      },
      {
        id: 's11',
        type: 'Course',
        category: 'courses',
        title: 'Monitoring & Decision-Making',
        blurb: 'How to choose signals, set thresholds, and avoid acting on noise.',
        price: '€199',
        seed: 21,
        href: externalLinks.payhip,
      },
      {
        id: 's12',
        type: 'Template',
        category: 'tools',
        title: 'Annual Plan Canvas',
        blurb: 'A printable A2 canvas for sketching a season at the table.',
        price: '€14',
        seed: 22,
        href: externalLinks.payhip,
      },
      {
        id: 's13',
        type: 'Print',
        category: 'products',
        title: 'Periodization Wall Map',
        blurb: 'A2 printed map of the framework — for the wall above your desk.',
        price: '€39',
        seed: 23,
        href: externalLinks.payhip,
      },
      {
        id: 's14',
        type: 'Notebook',
        category: 'products',
        title: 'AP Field Notebook',
        blurb: 'A pocket notebook prompted for session debriefs and weekly reviews.',
        price: '€24',
        seed: 24,
        href: externalLinks.payhip,
      },
    ],

    threads: [
      {
        id: 't1',
        handle: 'evelyn.k',
        role: 'S&C, Football',
        time: '2h',
        text: 'Anyone using readiness scores to gate sprint volume during in-season? Looking for thresholds that hold up.',
      },
      {
        id: 't2',
        handle: 'marko.p',
        role: 'Physio, Track',
        time: '6h',
        text: 'Sharing a return-to-play decision log we built off the monitoring template. Feedback welcome.',
      },
      {
        id: 't3',
        handle: 'jules.t',
        role: 'Combat sports',
        time: '14h',
        text: 'Question on residual fatigue during fight camp — how aggressively are you cutting CNS work in week 2?',
      },
    ],

    communityStats: [
      { value: '1,200+', label: 'Coaches & practitioners' },
      { value: '30+', label: 'Countries represented' },
      { value: 'Weekly', label: 'Live discussion threads' },
    ],

    tabs: [
      { id: 'tools', label: 'Tools' },
      { id: 'products', label: 'Products' },
      { id: 'courses', label: 'Courses' },
      { id: 'books', label: 'Books' },
    ],
  }),
  getters: {
    featurePost: (s) => s.posts.find((p) => p.variant === 'feature'),
    standardPosts: (s) => s.posts.filter((p) => p.variant === 'standard'),
    textPosts: (s) => s.posts.filter((p) => p.variant === 'text'),
  },
})
