import { defineStore } from 'pinia'

export const sources = {
  substack: { id: 'substack', name: 'Substack',  url: 'https://agileperiodization.substack.com/' },
  skool:    { id: 'skool',    name: 'Skool',     url: 'https://www.skool.com/agileperiodization' },
  payhip:   { id: 'payhip',   name: 'Payhip',    url: 'https://payhip.com/mjovanovic' },
  amazon:   { id: 'amazon',   name: 'Amazon',    url: 'https://amzn.to/4bQPUeM' },
  youtube:  { id: 'youtube',  name: 'YouTube',   url: 'https://www.youtube.com/@mladenjovanovic' },
}

export const externalLinks = {
  substack:  sources.substack.url,
  skool:     sources.skool.url,
  payhip:    sources.payhip.url,
  amazon:    sources.amazon.url,
  linkedin:  'https://www.linkedin.com/in/mladenjovanovic/',
  instagram: 'https://www.instagram.com/physical_prep/',
  github:    'https://github.com/mladenjovanovic',
}

export const useContentStore = defineStore('content', {
  state: () => ({
    items: [
      // ── Writing ────────────────────────────────────────────────────────────
      {
        id: 'p1',
        type: 'Essay',
        category: 'writing',
        title: 'Planning with intent, adjusting without panic',
        description: 'On the difference between a plan and the act of planning — and why the latter is what keeps coaches honest when the week starts breaking apart.',
        cover: { seed: 1 },
        price: null,
        url: sources.substack.url,
        source: 'substack',
        featured: false,
        date: 'Apr 28, 2026',
        readTime: '12 min',
        variant: 'feature',
      },
      {
        id: 'p2',
        type: 'Essay',
        category: 'writing',
        title: 'Why most periodization models fail in the real world',
        description: 'A field-tested look at where textbook templates collapse on contact with athletes, calendars, and weather.',
        cover: { seed: 2 },
        price: null,
        url: sources.substack.url,
        source: 'substack',
        featured: false,
        date: 'Apr 11, 2026',
        readTime: '9 min',
        variant: 'standard',
      },
      {
        id: 'p3',
        type: 'Tools',
        category: 'writing',
        title: 'Monitoring what matters',
        description: 'A practical framework for choosing the few signals you can actually act on.',
        cover: { seed: 3 },
        price: null,
        url: sources.substack.url,
        source: 'substack',
        featured: false,
        date: 'Mar 24, 2026',
        readTime: '14 min',
        variant: 'standard',
      },
      {
        id: 'p4',
        type: 'Field Notes',
        category: 'writing',
        title: 'Reading athletes: a field guide',
        description: 'What to look for before you ever open the spreadsheet.',
        cover: { seed: 4 },
        price: null,
        url: sources.substack.url,
        source: 'substack',
        featured: false,
        date: 'Mar 09, 2026',
        readTime: '7 min',
        variant: 'standard',
      },
      {
        id: 'p5',
        type: 'Essay',
        category: 'writing',
        title: 'Decision-making when the data is noisy',
        description: 'Heuristics, priors, and the cost of false certainty.',
        cover: { seed: 5 },
        price: null,
        url: sources.substack.url,
        source: 'substack',
        featured: false,
        date: 'Feb 22, 2026',
        readTime: '11 min',
        variant: 'standard',
      },
      {
        id: 'p6',
        type: 'Field Notes',
        category: 'writing',
        title: 'Skill acquisition for strength coaches',
        description: null,
        cover: { seed: 6 },
        price: null,
        url: sources.substack.url,
        source: 'substack',
        featured: false,
        date: 'Feb 03, 2026',
        readTime: '6 min',
        variant: 'text',
      },
      {
        id: 'p7',
        type: 'Essay',
        category: 'writing',
        title: 'The architecture of adaptation',
        description: null,
        cover: { seed: 7 },
        price: null,
        url: sources.substack.url,
        source: 'substack',
        featured: false,
        date: 'Jan 18, 2026',
        readTime: '10 min',
        variant: 'text',
      },

      // ── Courses ────────────────────────────────────────────────────────────
      {
        id: 's1',
        type: 'Course',
        category: 'courses',
        title: 'Agile Periodization — Foundations',
        description: 'A six-module video course on the operating framework behind real-world periodization.',
        cover: { seed: 11 },
        price: '€249',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },
      {
        id: 's2',
        type: 'Course',
        category: 'courses',
        title: 'Planning the Block, Not the Year',
        description: 'Short-cycle structure, adjustment heuristics, and decision logs.',
        cover: { seed: 12 },
        price: '€149',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },
      {
        id: 's11',
        type: 'Course',
        category: 'courses',
        title: 'Monitoring & Decision-Making',
        description: 'How to choose signals, set thresholds, and avoid acting on noise.',
        cover: { seed: 21 },
        price: '€199',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },

      // ── Books ──────────────────────────────────────────────────────────────
      {
        id: 's3',
        type: 'Book',
        category: 'books',
        title: 'Strength Training Manual',
        description: 'The two-volume reference on programming logic, set-and-rep schemes, and progression.',
        cover: { seed: 13 },
        price: '€59',
        url: sources.amazon.url,
        source: 'amazon',
        featured: false,
      },
      {
        id: 's4',
        type: 'Book',
        category: 'books',
        title: 'Bayesian Inference for Coaches',
        description: 'A coach-friendly introduction to thinking in probabilities.',
        cover: { seed: 14 },
        price: '€34',
        url: sources.amazon.url,
        source: 'amazon',
        featured: false,
      },

      // ── Tools ──────────────────────────────────────────────────────────────
      {
        id: 's5',
        type: 'Template',
        category: 'tools',
        title: 'Microcycle Planner',
        description: 'A working spreadsheet for laying out a week with intent, then adjusting it on Wednesday.',
        cover: { seed: 15 },
        price: '€29',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },
      {
        id: 's6',
        type: 'Template',
        category: 'tools',
        title: 'Athlete Monitoring Log',
        description: 'Wellness, load, readiness, and free-text notes in one practical sheet.',
        cover: { seed: 16 },
        price: '€19',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },
      {
        id: 's7',
        type: 'App',
        category: 'tools',
        title: 'AthletePulse',
        description: 'A lightweight tracking tool for daily readiness and weekly trends.',
        cover: { seed: 17 },
        price: '€9 / mo',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },
      {
        id: 's8',
        type: 'App',
        category: 'tools',
        title: 'LoadGraph',
        description: 'Plot acute and chronic load with a couple of clicks — built for terminal coaches.',
        cover: { seed: 18 },
        price: '€12 / mo',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },
      {
        id: 's12',
        type: 'Template',
        category: 'tools',
        title: 'Annual Plan Canvas',
        description: 'A printable A2 canvas for sketching a season at the table.',
        cover: { seed: 22 },
        price: '€14',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },

      // ── Products ───────────────────────────────────────────────────────────
      {
        id: 's9',
        type: 'Bundle',
        category: 'products',
        title: 'The Practitioner Bundle',
        description: 'Foundations course, both planner templates, and a year of AthletePulse.',
        cover: { seed: 19 },
        price: '€349',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },
      {
        id: 's10',
        type: 'Bundle',
        category: 'products',
        title: 'The Library Bundle',
        description: 'Every book and every essay collection — a single archive download.',
        cover: { seed: 20 },
        price: '€129',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },
      {
        id: 's13',
        type: 'Print',
        category: 'products',
        title: 'Periodization Wall Map',
        description: 'A2 printed map of the framework — for the wall above your desk.',
        cover: { seed: 23 },
        price: '€39',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },
      {
        id: 's14',
        type: 'Notebook',
        category: 'products',
        title: 'AP Field Notebook',
        description: 'A pocket notebook prompted for session debriefs and weekly reviews.',
        cover: { seed: 24 },
        price: '€24',
        url: sources.payhip.url,
        source: 'payhip',
        featured: false,
      },

      // ── Featured (Spotlight carousel) ─────────────────────────────────────
      {
        id: 'f1',
        type: 'Course',
        category: 'courses',
        title: 'Foundations 2.0 — the live cohort',
        description: 'Six weeks. Forty coaches. The operating framework taught the way it gets used in-season — with weekly office hours and a working planner you build alongside the lessons.',
        cover: { seed: 99 },
        price: '€749',
        url: sources.payhip.url,
        source: 'payhip',
        featured: true,
      },
      {
        id: 'f2',
        type: 'Book',
        category: 'books',
        title: 'Field Notes, Vol. II',
        description: 'A new collection of short-form observations from two seasons of in-field coaching. Practical, honest, and built for reading between sessions.',
        cover: { seed: 88 },
        price: '€34',
        url: sources.amazon.url,
        source: 'amazon',
        featured: true,
      },
      {
        id: 'f3',
        type: 'Workshop',
        category: 'courses',
        title: 'In-season planning workshop',
        description: 'A half-day live session on managing training around competition density. How to stay honest with load when the schedule stops cooperating.',
        cover: { seed: 77 },
        price: '€149',
        url: sources.payhip.url,
        source: 'payhip',
        featured: true,
      },
    ],

    video: {
      videoId: 'M7lc1UVf-VE',
      title: 'A field guide to reading athletes',
      duration: '14:08',
      caption: 'Mladen Jovanović · 2024 SBC Conference, Belgrade',
      description: 'How to read athlete state before a session even starts — what to look for in the warmup, how to weight subjective report against what you are seeing, and when to trust your read over the numbers.',
      href: 'https://www.youtube.com/watch?v=M7lc1UVf-VE',
      channelHref: 'https://www.youtube.com/@mladenjovanovic',
    },

    channels: [
      { id: 'planning',       label: '# planning' },
      { id: 'monitoring',     label: '# monitoring' },
      { id: 'return-to-play', label: '# return-to-play' },
      { id: 'book-club',      label: '# book-club' },
    ],

    threads: [
      // planning
      { id: 't1', channel: 'planning', handle: 'evelyn.k',  role: 'S&C · Football',     time: '2h',  replies: 14, text: 'Anyone using readiness scores to gate sprint volume during in-season? Looking for thresholds that actually hold up across a long schedule.' },
      { id: 't2', channel: 'planning', handle: 'jakob.r',   role: 'Athletics · Throws',  time: '5h',  replies: 8,  text: 'What does your minimum viable week look like when the schedule collapses to 3 days? Asking for the next 6 weeks.' },
      { id: 't3', channel: 'planning', handle: 'sara.v',    role: 'Hockey · S&C',        time: '1d',  replies: 21, text: 'Has anyone mapped the barbell strategy to block design — safe base block plus small experimental block rather than undulating everything?' },
      // monitoring
      { id: 't4', channel: 'monitoring', handle: 'marko.p', role: 'Physio · Track',      time: '6h',  replies: 19, text: 'Sharing a return-to-play decision log we built off the monitoring template. Feedback very welcome.' },
      { id: 't5', channel: 'monitoring', handle: 'claire.m',role: 'S&C · Rugby',         time: '9h',  replies: 11, text: 'Rolling 28-day load is giving me cleaner signals than ACWR ever did. Anyone else moved away from the ratio entirely?' },
      { id: 't6', channel: 'monitoring', handle: 'niko.a',  role: 'Basketball · Perf',   time: '2d',  replies: 6,  text: 'We cut subjective wellness to one question — overall feel 1–10. Three months in and it is more actionable than the full questionnaire combo.' },
      // return-to-play
      { id: 't7', channel: 'return-to-play', handle: 'jules.t', role: 'Combat sports',   time: '14h', replies: 17, text: 'Question on residual fatigue during fight camp — how aggressively are you cutting CNS work in week 2 of a 4-week camp?' },
      { id: 't8', channel: 'return-to-play', handle: 'ana.d',   role: 'Physio · Football',time: '1d', replies: 23, text: 'Criteria-based vs time-based RTP — what decision triggers do you actually use in practice vs what the literature says?' },
      { id: 't9', channel: 'return-to-play', handle: 'liam.f',  role: 'S&C · Cricket',   time: '3d',  replies: 9,  text: 'Anyone have a template for the deload-to-ramp sequence after a soft tissue injury? Something I can hand off to the physio.' },
      // book-club
      { id: 't10', channel: 'book-club', handle: 'petra.s', role: 'Sports Sci · Swim',   time: '4h',  replies: 12, text: '"Models are maps, not territory" hits differently each time. Re-reading the Foundations notes from the course this week.' },
      { id: 't11', channel: 'book-club', handle: 'oskar.l', role: 'Strength Coach',       time: '12h', replies: 7,  text: 'Taleb on robustness vs optimisation — has anyone applied the barbell concept directly to program structure, not just intensity distribution?' },
      { id: 't12', channel: 'book-club', handle: 'mei.w',   role: 'Tennis · Performance', time: '2d',  replies: 15, text: 'Reading Cynefin for the first time. The sense-respond vs analyse-respond split is exactly what the agile framework is built on.' },
    ],

    communityStats: [
      { value: '1,200+', label: 'Coaches & practitioners' },
      { value: '30+', label: 'Countries represented' },
      { value: 'Weekly', label: 'Live discussion threads' },
    ],

    tabs: [
      { id: 'tools', label: 'Tools' },
      { id: 'products', label: 'Products' },
      { id: 'courses', label: 'Courses' },
      { id: 'books', label: 'Books' },
    ],

    // ── Hero Banner items ──────────────────────────────────────────────────
    // All fields optional. video takes priority over coverImage (never both).
    // layout: 'overlay' | 'split-end' | 'split-start' | 'stacked'
    heroItems: [
      {
        id: 'h1',
        pinned: true,
        layout: 'overlay',
        title: 'Foundations 2.0 — <em>the live cohort.</em>',
        description: 'Six weeks. Forty coaches. The operating framework taught the way it gets used in-season — with weekly office hours and a working planner you build alongside the lessons.',
        coverImage: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=1600&q=85',
        videoUrl: null,
        ctaUrl: 'https://payhip.com/mjovanovic',
        ctaLabel: 'Get your spot',
        price: '€749',
      },
      {
        id: 'h2',
        pinned: true,
        layout: 'split-end',
        title: 'Field Notes, <em>Vol. II</em>',
        description: 'A new collection of short-form observations from two seasons of in-field coaching. Practical, honest, built for reading between sessions.',
        coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=900&q=85',
        videoUrl: null,
        ctaUrl: 'https://amzn.to/4bQPUeM',
        ctaLabel: 'Get the book',
        price: '€34',
      },
      {
        id: 'h3',
        pinned: true,
        layout: 'split-start',
        title: 'A field guide to <em>reading athletes.</em>',
        description: 'How to read athlete state before a session starts — what to look for in the warmup, when to trust your read over the numbers.',
        coverImage: null,
        videoUrl: 'https://www.youtube.com/watch?v=M7lc1UVf-VE',
        ctaUrl: null,
        ctaLabel: null,
        price: null,
      },
      {
        id: 'h4',
        pinned: true,
        layout: 'stacked',
        title: 'The Practitioner <em>Bundle.</em>',
        description: 'Foundations course, both planner templates, and a year of AthletePulse — everything you need to run a principled training operation.',
        coverImage: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1600&q=85',
        videoUrl: null,
        ctaUrl: 'https://payhip.com/mjovanovic',
        ctaLabel: 'See the bundle',
        price: '€349',
      },
    ],
  }),

  getters: {
    featured: (s) => s.items.filter((i) => i.featured),
    pinnedHeroItems: (s) => s.heroItems.filter((i) => i.pinned),
    articles: (s) => s.items.filter((i) => i.category === 'writing'),
    products: (s) => s.items.filter((i) => i.category !== 'writing'),
    productsByCategory: (s) => (cat) => s.items.filter((i) => i.category === cat),

    featureArticle: (s) => s.items.find((i) => i.category === 'writing' && i.variant === 'feature'),
    standardArticles: (s) => s.items.filter((i) => i.category === 'writing' && i.variant === 'standard'),
    textArticles: (s) => s.items.filter((i) => i.category === 'writing' && i.variant === 'text'),
  },
})
